###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# CP4BA 22.0.2 IF006 catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cp4a-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp4a-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cp-automation-catalog@sha256:63c01ab49ba53c27ab99ede7cc5db2cb687e8ae7b308a74b90c421a296395242
  updateStrategy:
    registryPoll:
      interval: 45m
---
# IBM Automation Foundation Base 1.3.14
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cp-automation-foundation-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Automation Foundation Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cp-automation-foundation-catalog@sha256:c510e7b9cb3c6fdfac3a05c2f97b12e1f0187431b4466d5707d9e48b3dfd9ca1
  updateStrategy:
    registryPoll:
      interval: 45m
---
# IBM Automation Foundation Core 1.3.14
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-automation-foundation-core-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Automation Foundation Core Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-automation-foundation-core-catalog@sha256:c3179bad29705422354c5ef656ee464c5322cca09010fff9b5bf86a9ad06aab4
  updateStrategy:
    registryPoll:
      interval: 45m
---
# IBM Cloud Foundational Services 3.23.4
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    bedrock_catalogsource_priority: '1'
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBMCS Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-common-service-catalog@sha256:cc3491ee7b448c3c8db43242d13e9d5d13a37ad9e67d166744d9b162887ed7e7
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# IBM Business Teams Service version 3.26.0
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    bedrock_catalogsource_priority: '1'
  name: bts-operator
  namespace: openshift-marketplace
spec:
  displayName: BTS Operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-bts-operator-catalog@sha256:0043ccbf6ae8a6901182fb1e45bc580b8a81be67b951897e9dc4ef6495a94f57
  updateStrategy:
    registryPoll:
      interval: 45m
---
# Cloud Native PostgresSQL 4.11.0
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    bedrock_catalogsource_priority: '1'
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
spec:
  displayName: Cloud Native Postgresql Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:642aba4b78bcadd8f1d5e1f9d05d8484e2934d914a5b6d67435f3e98082d7592
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100